apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  replicas: 3
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: docker.ops.dev.invent-360.com/invent360/ng-app:latest
        ports:
        - containerPort: 4200
          name: server